using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json;
using main_client.Ventura.StreamObject.DataModel;
using main_client.StreamObject.WorldData;
using main_client.Ventura.Jobs.ListJobs;

namespace main_client.Ventura.Constant
{
    public class Constant
    {
        public static int HashcodeEventLocal = 0;


        public static JsonSerializerSettings setting = new JsonSerializerSettings()
        {
            NullValueHandling = NullValueHandling.Ignore,
            Formatting = Formatting.None,
        };

        public static void Notify(string text)
        {
            RAGE.Game.Ui.SetNotificationTextEntry("STRING");
            RAGE.Game.Ui.AddTextComponentSubstringPlayerName(text);
            RAGE.Game.Ui.DrawNotification(false, false);
        }

        public enum AnimationFlags
        {
            Loop = 1 << 0,
            StopOnLastFrame = 1 << 1,
            OnlyAnimateUpperBody = 1 << 4,
            AllowPlayerControl = 1 << 5,
            Cancellable = 1 << 7
        };

        public enum UpdateFlagsClient
        {
            Player = 0x20 << 3,
            Vehicle = 0x21 << 3,
            Item = 0x22 << 3,
            WorldJobsActivityData = 0x01 << 2,
            WorldAnimationData = 0x02 << 2,
            WorldSceneData = 0x03 << 2,
            WorldSeatData = 0x04 << 2,
            WorldBodyData = 0x05 << 2,
            WorldClothData = 0x06 << 2,
            WorldVehiculeData = 0x07 << 2,
            WorldObjectData = 0x08 << 2,
            WorldAttachData = 0x09 << 2,
            WorldFightData = 0x0A << 2,
            WorldIdentityData = 0x0B << 2,
            WorldUserData = 0x0C << 2,
            WorldTattooData = 0x0D << 2,
            WorldRigidBodyData = 0x0E << 2,
            WorldDoorData = 0x0F << 2,
            //WorldPedData = 0x10 << 2,
        }

        public static dynamic Cast(dynamic source, Type dest)
        {
            return Convert.ChangeType(source, dest);
        }

        public enum InteractionFlags
        {
            OwnInventory,
            ClosestCarInventory,
            GetClosestPlant,
            GetClosestObject,
            CheckClosestPlayer,
            GiveIdCardClosestPlayer,
            GiveDriveCardClosestPlayer,
            GiveLSPDCardClosestPlayer,
            GiveLSDHCardClosestPlayer,
            GiveCarCardClosestPlayer,
            ClosestObjectInventory,
            OpenHouse,
            CloseHouse,
            RingHouse,
            OpenCar,
            CloseCar,
            OpenDoorCar,
            CloseDoorCar,
            CloseBootCar,
            OpenBootCar,
            OnEngineCar,
            OffEngineCar,
            OnLightCar,
            OffLightCar,
            OnRadarCar,
            OffRadarCar,
            OffRadioCar,
            OnRadioCar,
            OnJobsAction,
            OffJobsAction,
            OffJobsService,
            OnJobsService,
            OnJobsComputer,
            OffJobsComputer,
            SeatChair,
            UnSeatChair,
            OpenDoorOutside,
            CloseDoorOutside,
        }


        public static List<Type> table_type = new List<Type>()
        {
        /*    typeof(WorldJobsActivityData),
            typeof(WorldAnimationData),
            typeof(WorldSceneData),
            typeof(WorldBodyData),
            typeof(WorldClothData),
            typeof(WorldVehicleData),
            typeof(WorldObjectData),
            typeof(WorldAttachData),
            typeof(WorldIdentityData),
            typeof(WorldUserData),
            typeof(WorldTattooData),*/
        };

        public static List<Tuple<string, string>> overlayHair = new List<Tuple<string, string>>() {
            new Tuple<string, string>("multiplayer_overlays", "FM_Tat_Award_F_000" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_Tat_000_F" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_tat_004_F" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_tat_017_F" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_tat_017_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_MP_Biker_Tat_009_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_MP_Biker_Tat_038_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_MP_Biker_Tat_051_F" ),
            new Tuple<string, string>("mpgunrunning_overlays", "MP_Gunrunning_Tattoo_003_F" ),
            new Tuple<string, string>("mpgunrunning_overlays", "MP_Smuggler_Tattoo_011_F" ),
            new Tuple<string, string>("mpgunrunning_overlays", "MP_Smuggler_Tattoo_012_F" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_F_Hair_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_F_Hair_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_F_Hair_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_F_Hair_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_F_Hair_e" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_017_a" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_017_b" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_017_c" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_017_d" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_017_e" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_020_a" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_020_b" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_020_c" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_020_d" ),
            new Tuple<string, string>("mphipster_overlays", "FM_F_Hair_020_e" ),
            new Tuple<string, string>("mphipster_overlays", "FM_Hip_F_Hair_000_a" ),
            new Tuple<string, string>("mphipster_overlays", "FM_Hip_F_Hair_000_b" ),
            new Tuple<string, string>("mphipster_overlays", "FM_Hip_F_Hair_000_c" ),
            new Tuple<string, string>("mphipster_overlays", "FM_Hip_F_Hair_000_d" ),
            new Tuple<string, string>("mphipster_overlays", "FM_Hip_F_Hair_000_e" ),
            new Tuple<string, string>("mplowrider_overlays", "LR_F_Hair_000" ),
            new Tuple<string, string>("mplowrider_overlays", "LR_F_Hair_001" ),
            new Tuple<string, string>("mplowrider_overlays", "LR_F_Hair_002" ),
            new Tuple<string, string>("mpxmas_604490_overlays", "Hair_014_Fix" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_005_a" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_005_b" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_005_c" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_005_d" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_005_e" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_006_a" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_006_b" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_006_c" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_006_d" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_006_e" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_013_a" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_013_b" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_013_c" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_013_d" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_013_e" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_014_a" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_014_b" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_014_c" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_014_d" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_014_e" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_long_a" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_long_b" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_long_c" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_long_d" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_long_e" ),
            new Tuple<string, string>("mpbeach_overlays", "FM_Hair_Fuzz" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_003_a" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_003_b" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_003_c" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_003_d" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_F_Hair_003_e" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_001" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_002" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_003" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_004" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_005" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_006" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_007" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_008" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_009" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_010" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_011" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_012" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_013" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_014" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_F_Hair_015" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_001" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_002" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_003" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_004" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_005" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_006" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_007" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_008" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_009" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_010" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_011" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_012" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_013" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_014" ),
            new Tuple<string, string>("multiplayer_overlays", "NG_M_Hair_015" ),
            new Tuple<string, string>("multiplayer_overlays", "NGBea_F_Hair_000" ),
            new Tuple<string, string>("multiplayer_overlays", "NGBea_F_Hair_001" ),
            new Tuple<string, string>("multiplayer_overlays", "NGBea_M_Hair_000" ),
            new Tuple<string, string>("multiplayer_overlays", "NGBea_M_Hair_001" ),
            new Tuple<string, string>("multiplayer_overlays", "NGBus_F_Hair_000" ),
            new Tuple<string, string>("multiplayer_overlays", "NGBus_F_Hair_001" ),
            new Tuple<string, string>("multiplayer_overlays", "NGBus_M_Hair_000" ),
            new Tuple<string, string>("multiplayer_overlays", "NGBus_M_Hair_001" ),
            new Tuple<string, string>("multiplayer_overlays", "NGHip_F_Hair_000" ),
            new Tuple<string, string>("multiplayer_overlays", "NGHip_F_Hair_001" ),
            new Tuple<string, string>("multiplayer_overlays", "NGHip_M_Hair_000" ),
            new Tuple<string, string>("multiplayer_overlays", "NGHip_M_Hair_001" ),
            new Tuple<string, string>("multiplayer_overlays", "NGInd_F_Hair_000" ),
            new Tuple<string, string>("multiplayer_overlays", "NGInd_M_Hair_000" ),
            new Tuple<string, string>("mplowrider2_overlays", "LR_F_Hair_003" ),
            new Tuple<string, string>("mplowrider2_overlays", "LR_F_Hair_004" ),
            new Tuple<string, string>("mplowrider2_overlays", "LR_F_Hair_006" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_000_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_001_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_002_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_003_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_004_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_005_F" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_006_F" ),
            new Tuple<string, string>("mpgunrunning_overlays", "MP_Gunrunning_Hair_F_000_F" ),
            new Tuple<string, string>("mpgunrunning_overlays", "MP_Gunrunning_Hair_F_001_F" ),
            new Tuple<string, string>("multiplayer_overlays", "FM_Tat_Award_M_000" ),
            new Tuple<string, string>("mpbeach_overlays", "MP_Bea_M_Head_000" ),
            new Tuple<string, string>("mpbeach_overlays", "MP_Bea_M_Head_001" ),
            new Tuple<string, string>("mpbeach_overlays", "MP_Bea_M_Head_002" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_Tat_000_M" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_Tat_001_M" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_Tat_002_M" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_tat_017_M" ),
            new Tuple<string, string>("mpstunt_overlays", "MP_MP_Stunt_tat_042_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_MP_Biker_Tat_009_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_MP_Biker_Tat_038_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_MP_Biker_Tat_051_M" ),
            new Tuple<string, string>("mpgunrunning_overlays", "MP_Gunrunning_Tattoo_003_M" ),
            new Tuple<string, string>("mpsmuggler_overlays", "MP_Smuggler_Tattoo_011_M" ),
            new Tuple<string, string>("mpsmuggler_overlays", "MP_Smuggler_Tattoo_012_M" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_000_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_000_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_000_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_000_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_000_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_001_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_001_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_001_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_001_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Bus_M_Hair_001_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Disc_M_Hair_001_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Disc_M_Hair_001_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Disc_M_Hair_001_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Disc_M_Hair_001_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Disc_M_Hair_001_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_000_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_000_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_000_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_000_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_000_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_001_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_001_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_001_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_001_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_Hip_M_Hair_001_e" ),
            new Tuple<string, string>("mplowrider_overlays", "LR_M_Hair_000" ),
            new Tuple<string, string>("mplowrider_overlays", "LR_M_Hair_001" ),
            new Tuple<string, string>("mplowrider_overlays", "LR_M_Hair_002" ),
            new Tuple<string, string>("mplowrider_overlays", "LR_M_Hair_003" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_001_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_001_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_001_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_001_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_001_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_003_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_003_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_003_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_003_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_003_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_006_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_006_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_006_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_006_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_006_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_008_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_008_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_008_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_008_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_008_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_long_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_long_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_long_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_long_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_M_Hair_long_e" ),
            new Tuple<string, string>("mpbeach_overlays", "FM_Hair_Fuzz" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_F_Hair_003_a" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_F_Hair_003_b" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_F_Hair_003_c" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_F_Hair_003_d" ),
            new Tuple<string, string>("mpbusiness_overlays", "FM_F_Hair_003_e" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_001" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_002" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_003" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_004" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_005" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_006" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_007" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_008" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_009" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_010" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_011" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_012" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_013" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_014" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_F_Hair_015" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_001" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_002" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_003" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_004" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_005" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_006" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_007" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_008" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_009" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_010" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_011" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_012" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_013" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_014" ),
            new Tuple<string, string>("mpbusiness_overlays", "NG_M_Hair_015" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGBea_F_Hair_000" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGBea_F_Hair_001" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGBea_M_Hair_000" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGBea_M_Hair_001" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGBus_F_Hair_000" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGBus_F_Hair_001" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGHip_F_Hair_000" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGHip_F_Hair_001" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGHip_M_Hair_000" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGHip_M_Hair_001" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGInd_F_Hair_000" ),
            new Tuple<string, string>("mpbusiness_overlays", "NGInd_M_Hair_000" ),
            new Tuple<string, string>("mplowrider2_overlays", "LR_M_Hair_004" ),
            new Tuple<string, string>("mplowrider2_overlays", "LR_M_Hair_005" ),
            new Tuple<string, string>("mplowrider2_overlays", "LR_M_Hair_006" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_000_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_001_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_002_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_003_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_004_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_005_M" ),
            new Tuple<string, string>("mpbiker_overlays", "MP_Biker_Hair_006_M" ),
            new Tuple<string, string>("mpgunrunning_overlays", "MP_Gunrunning_Hair_M_000_M" ),
            new Tuple<string, string>("mpgunrunning_overlays", "MP_Gunrunning_Hair_M_001_M" ),

        };

        public static List<string> table_event_name = new List<string>()
        {
            "WorldJobsActivityData",
            "WorldAnimationData",
            "WorldSceneData",
            "WorldSeatData",
            "WorldBodyData",
            "WorldClothData",
            "WorldVehicleData",
            "WorldObjectData",
            "WorldAttachData",
            "WorldFightData",
            "WorldIdentityData",
            "WorldUserData",
            "WorldTattooData",
            "WorldRigidBodyData",
            "WorldDoorData",
            //"WorldPedData",
        };

        public static List<string> table_data_name = new List<string>()
        {
            "StreamJobsActivityData",
            "StreamAnimationData",
            "StreamSceneData",
            "StreamSeatData",
            "StreamBodyData",
            "StreamClothData",
            "StreamVehicleData",
            "StreamObjectData",
            "StreamAttachData",
            "StreamFightData",
            "StreamIdentityData",
            "StreamUserData",
            "StreamTattooData",
            "StreamRigidBodyData",
            "StreamDoorData",
            //"StreamPedData",
        };


        public static List<Type> table_jobs_type = new List<Type>()
        {
            //typeof(ListClothShopData),
            /*typeof(ListHomeData),
            typeof(ListBarberShopData),
            typeof(ListLSPDData),
            typeof(ListLSPHData),
            typeof(ListBankData),
            typeof(ListAtmData),
            typeof(ListLSCustomData),
            typeof(ListUnicornData),
            typeof(ListBikeRiderData),
            typeof(ListBennysCustomData),
            typeof(ListJudgeData),
            typeof(ListWeazelNewsData),
            typeof(ListGaragePublicData),
            typeof(ListGaragePrivateData),
            typeof(ListConcessShopData),
            typeof(ListLawyerData),
            typeof(ListGasolineShopData),
            typeof(ListLostData),
            typeof(ListConcessData),
            typeof(ListFishData),
            typeof(ListTaxiData),
            typeof(ListVehicleShooterData),
            typeof(ListHomeJobsData),
            typeof(ListElectricienData),
            typeof(ListVitreurData),
            typeof(ListDoorData),*/
        };

        public enum UpdateJobsClient
        {
            UpdateListClothShopData,
            UpdateListHomeData,
            UpdateListBarberShopData,
            UpdateListLSPDData,
            UpdateListLSPHData,
            UpdateListBankData,
            UpdateListAtmData,
            UpdateListLSCustomData,
            UpdateListUnicornData,
            UpdateListBikeRiderData,
            UpdateListBennysCustomData,
            UpdateListJudgeData,
            UpdateListWeazelNewsData,
            UpdateListGaragePublicData,
            UpdateListGaragePrivateData,
            UpdateListConcessShopData,
            UpdateListLawyerData,
            UpdateListGasolineShopData,
            UpdateListLostData,
            UpdateListConcessData,
            UpdateListFishData,
            UpdateListTaxiData,
            UpdateListVehicleShooterData,
            UpdateListHomeJobsData,
            UpdateListElectricienData,
            UpdateListVitreurData,
            UpdateListDoorData,
        }



        public static List<string> table_jobs_data = new List<string>() {
            "UpdateListClothShop",
            "UpdateListHomeData",
            "UpdateListBarberShopData",
            "UpdateListLSPDData",
            "UpdateListLSPHData",
            "UpdateListBankData",
            "UpdateListAtmData",
            "UpdateListLSCustomData",
            "UpdateListUnicornData",
            "UpdateListBikeRiderData",
            "UpdateListBennysCustomData",
            "UpdateListJudgeData",
            "UpdateListWeazelNewsData",
            "UpdateListGaragePublicData",
            "UpdateListGaragePrivateData",
            "UpdateListConcessShopData",
            "UpdateListLawyerData",
            "UpdateListGasolineShopData",
            "UpdateListLostData",
            "UpdateListConcessData",
            "UpdateListFishData",
            "UpdateListTaxiData",
            "UpdateListVehicleShooterData",
            "UpdateListHomeJobsData",
            "UpdateListElectricienData",
            "UpdateListVitreurData",
            "UpdateListDoorData",
        };


        public static List<string> BrowserList = new List<string>() {
                "InteractionForm",
                "InventoryForm",
        };

        public static List<string> ListDoor = new List<string>()
        {
                "apa_heist_apart2_door",
                "apa_mp_apa_yacht_door",
                "apa_mp_apa_yacht_door2",
                "apa_p_mp_door_01",
                "apa_p_mp_door_02",
                "apa_p_mp_door_03",
                "apa_p_mp_door_04",
                "apa_p_mp_door_05",
                "apa_p_mp_door_06",
                "apa_p_mp_door_07",
                "apa_p_mp_door_apart_door",
                "apa_p_mp_door_apart_door_black",
                "apa_p_mp_door_apartfrt_door",
                "apa_p_mp_door_apartfrt_door_black",
                "apa_p_mp_door_mpa",
                "apa_p_mp_door_mpa2_frnt",
                "apa_p_mp_door_stilt_door",
                "apa_p_mp_door_stilt_doorfrnt",
                "apa_p_mp_h_showerdoor_s",
                "apa_p_mp_yacht_bathroomdoor",
                "apa_p_mp_yacht_door",
                "apa_p_mp_yacht_door_01",
                "apa_p_mp_yacht_door_02",
                "apa_prop_apa_bankdoor_new",
                "apa_prop_apa_cutscene_doora",
                "apa_prop_apa_cutscene_doorb",
                "apa_prop_apa_cutscene_showerdoor",
                "apa_prop_hei_bankdoor_new",
                "apa_prop_heist_cutscene_doora",
                "apa_prop_heist_cutscene_doorb",
                "apa_prop_ss1_mpint_door_l",
                "apa_prop_ss1_mpint_door_r",
                "apa_v_ilev_fh_bedrmdoor",
                "apa_v_ilev_fh_heistdoor1",
                "apa_v_ilev_fh_heistdoor2",
                "apa_v_ilev_ss_door2",
                "apa_v_ilev_ss_door7",
                "apa_v_ilev_ss_door8",
                "bkr_prop_biker_door_entry",
                "bkr_prop_biker_safedoor_01a",
                "des_door_root",
                "des_door_start",
                "des_frenchdoors_end",
                "des_frenchdoors_root",
                "des_frenchdoors_rootb",
                "des_frenchdoors_start",
                "des_hospitaldoors_end",
                "des_hospitaldoors_skin_root1",
                "des_hospitaldoors_skin_root2",
                "des_hospitaldoors_skin_root3",
                "des_hospitaldoors_start",
                "des_hospitaldoors_start_old",
                "des_plog_door_end",
                "des_plog_door_root",
                "des_plog_door_start",
                "des_vaultdoor001_root001",
                "des_vaultdoor001_root002",
                "des_vaultdoor001_root003",
                "des_vaultdoor001_root004",
                "des_vaultdoor001_root005",
                "des_vaultdoor001_root006",
                "des_vaultdoor001_skin001",
                "des_vaultdoor001_start",
                "ex_p_mp_door_apart_door",
                "ex_p_mp_door_apart_door_black",
                "ex_p_mp_door_apart_door_black_s",
                "ex_p_mp_door_apart_door_s",
                "ex_p_mp_door_apart_doorbrown_s",
                "ex_p_mp_door_apart_doorbrown01",
                "ex_p_mp_door_apart_doorwhite01",
                "ex_p_mp_door_apart_doorwhite01_s",
                "ex_p_mp_door_office_door01",
                "ex_p_mp_door_office_door01_s",
                "ex_p_mp_h_showerdoor_s",
                "ex_prop_door_arcad_ent_l",
                "ex_prop_door_arcad_ent_r",
                "ex_prop_door_arcad_roof_l",
                "ex_prop_door_arcad_roof_r",
                "ex_prop_door_lowbank_ent_l",
                "ex_prop_door_lowbank_ent_r",
                "ex_prop_door_lowbank_roof",
                "ex_prop_door_maze2_ent_l",
                "ex_prop_door_maze2_ent_r",
                "ex_prop_door_maze2_rf_l",
                "ex_prop_door_maze2_rf_r",
                "ex_prop_door_maze2_roof",
                "ex_prop_exec_office_door01",
                "ex_prop_safedoor_office1a_l",
                "ex_prop_safedoor_office1a_r",
                "ex_prop_safedoor_office1b_l",
                "ex_prop_safedoor_office1b_r",
                "ex_prop_safedoor_office1c_l",
                "ex_prop_safedoor_office1c_r",
                "ex_prop_safedoor_office2a_l",
                "ex_prop_safedoor_office2a_r",
                "ex_prop_safedoor_office3a_l",
                "ex_prop_safedoor_office3a_r",
                "ex_prop_safedoor_office3c_l",
                "ex_prop_safedoor_office3c_r",
                "gr_prop_gr_bunkeddoor",
                "gr_prop_gr_bunkeddoor_col",
                "gr_prop_gr_bunkeddoor_f",
                "gr_prop_gr_doorpart",
                "gr_prop_gr_doorpart_f",
                "gr_prop_inttruck_door_01",
                "gr_prop_inttruck_door_static",
                "gr_prop_inttruck_doorblocker",
                "hei_heist_apart2_door",
                "hei_prop_bh1_08_hdoor",
                "hei_prop_cntrdoor_mph_l",
                "hei_prop_cntrdoor_mph_r",
                "hei_prop_dt1_20_mph_door_l",
                "hei_prop_dt1_20_mph_door_r",
                "hei_prop_hei_bankdoor_new",
                "hei_prop_hei_shack_door",
                "hei_prop_heist_carrierdoorl",
                "hei_prop_heist_carrierdoorr",
                "hei_prop_heist_cutscene_doora",
                "hei_prop_heist_cutscene_doorb",
                "hei_prop_heist_cutscene_doorc_l",
                "hei_prop_heist_cutscene_doorc_r",
                "hei_prop_heist_lockerdoor",
                "hei_prop_heist_safedepdoor",
                "hei_prop_heist_sec_door",
                "hei_prop_sm_14_mph_door_l",
                "hei_prop_sm_14_mph_door_r",
                "hei_prop_ss1_mpint_door_l",
                "hei_prop_ss1_mpint_door_r",
                "hei_prop_sync_door_06",
                "hei_prop_sync_door_08",
                "hei_prop_sync_door_09",
                "hei_prop_sync_door_10",
                "hei_prop_sync_door01a",
                "hei_prop_sync_door01b",
                "hei_prop_sync_door02a",
                "hei_prop_sync_door02b",
                "hei_prop_sync_door03",
                "hei_prop_sync_door04",
                "hei_prop_sync_door05a",
                "hei_prop_sync_door05b",
                "hei_prop_sync_door07",
                "hei_v_ilev_fh_heistdoor1",
                "hei_v_ilev_fh_heistdoor2",
                "imp_prop_impexp_car_door_01a",
                "imp_prop_impexp_car_door_02a",
                "imp_prop_impexp_car_door_03a",
                "imp_prop_impexp_car_door_04a",
                "imp_prop_impexp_car_door_05a",
                "imp_prop_impexp_door_vid",
                "imp_prop_impexp_liftdoor_l",
                "imp_prop_impexp_liftdoor_r",
                "lr_prop_boathousedoor_l",
                "lr_prop_boathousedoor_r",
                "lr_prop_supermod_door_01",
                "p_bs_map_door_01_s",
                "p_cablecar_s_door_l",
                "p_cablecar_s_door_r",
                "p_cs_locker_door_01",
                "p_cs_locker_door_01b",
                "p_cs_locker_door_02",
                "p_cs1_14b_train_esdoor",
                "p_cut_door_01",
                "p_cut_door_02",
                "p_cut_door_03",
                "p_disp_02_door_01",
                "p_fin_vaultdoor_s",
                "p_gar_door_01_s",
                "p_gar_door_02_s",
                "p_gar_door_03_s",
                "p_gdoor1_s",
                "p_gdoor1colobject_s",
                "p_gdoortest_s",
                "p_hw1_22_doors_s",
                "p_jewel_door_l",
                "p_jewel_door_r1",
                "p_mp_door_01",
                "p_mp_door_02",
                "p_mp_door_03",
                "p_mp_door_04",
                "p_mp_door_05",
                "p_mp_door_06",
                "p_mp_door_07",
                "p_mp_showerdoor_s",
                "p_po1_01_doorm_s",
                "pil_prop_fs_safedoor",
                "pop_v_bank_door_l",
                "pop_v_bank_door_r",
                "port_xr_door_01",
                "port_xr_door_04",
                "port_xr_door_05",
                "port_xr_lightdoor",
                "prop_a_trailer_door_01",
                "prop_bank_vaultdoor",
                "prop_barn_door_l",
                "prop_barn_door_r",
                "prop_bh1_44_door_01l",
                "prop_bh1_44_door_01r",
                "prop_bh1_48_backdoor_l",
                "prop_bh1_48_backdoor_r",
                "prop_bhhotel_door_l",
                "prop_bhhotel_door_r",
                "prop_biolab_g_door",
                "prop_bs_map_door_01",
                "prop_car_door_01",
                "prop_car_door_02",
                "prop_car_door_03",
                "prop_car_door_04",
                "prop_casino_door_01l",
                "prop_casino_door_01r",
                "prop_ch_025c_g_door_01",
                "prop_ch1_07_door_01l",
                "prop_ch1_07_door_01r",
                "prop_ch1_07_door_02l",
                "prop_ch1_07_door_02r",
                "prop_ch2_05d_g_door",
                "prop_ch2_07b_20_g_door",
                "prop_ch2_09b_door",
                "prop_ch2_09c_garage_door",
                "prop_ch3_01_trlrdoor_l",
                "prop_ch3_01_trlrdoor_r",
                "prop_ch3_04_door_01l",
                "prop_ch3_04_door_01r",
                "prop_ch3_04_door_02",
                "prop_cntrdoor_ld_l",
                "prop_cntrdoor_ld_r",
                "prop_com_gar_door_01",
                "prop_com_ls_door_01",
                "prop_conslift_door",
                "prop_container_door_mb_l",
                "prop_container_door_mb_r",
                "prop_control_rm_door_01",
                "prop_cs_freightdoor_l1",
                "prop_cs_freightdoor_r1",
                "prop_cs_fridge_door",
                "prop_cs_ice_locker_door_l",
                "prop_cs_ice_locker_door_r",
                "prop_cs4_05_tdoor",
                "prop_cs4_11_door",
                "prop_cs6_03_door_l",
                "prop_cs6_03_door_r",
                "prop_cub_door_lifeblurb",
                "prop_damdoor_01",
                "prop_door_01",
                "prop_door_balcony_frame",
                "prop_door_balcony_left",
                "prop_door_balcony_right",
                "prop_door_bell_01",
                "prop_dt1_20_mp_door_l",
                "prop_dt1_20_mp_door_r",
                "prop_epsilon_door_l",
                "prop_epsilon_door_r",
                "prop_faceoffice_door_l",
                "prop_faceoffice_door_r",
                "prop_gar_door_01",
                "prop_gar_door_02",
                "prop_gar_door_03",
                "prop_gar_door_03_ld",
                "prop_gar_door_04",
                "prop_gar_door_05",
                "prop_gar_door_05_l",
                "prop_gar_door_05_r",
                "prop_gar_door_a_01",
                "prop_gar_door_plug",
                "prop_gascyl_ramp_door_01",
                "prop_grumandoor_l",
                "prop_grumandoor_r",
                "prop_hanger_door_1",
                "prop_hospital_door_l",
                "prop_hospital_door_r",
                "prop_hospitaldoors_start",
                "prop_hw1_03_gardoor_01",
                "prop_hw1_04_door_l1",
                "prop_hw1_04_door_r1",
                "prop_hw1_23_door",
                "prop_id_21_gardoor_01",
                "prop_id_21_gardoor_02",
                "prop_id2_11_gdoor",
                "prop_indus_meet_door_l",
                "prop_indus_meet_door_r",
                "prop_kt1_06_door_l",
                "prop_kt1_06_door_r",
                "prop_kt1_10_mpdoor_l",
                "prop_kt1_10_mpdoor_r",
                "prop_ld_bankdoors_01",
                "prop_ld_bankdoors_02",
                "prop_ld_jail_door",
                "prop_ld_vault_door",
                "prop_magenta_door",
                "prop_map_door_01",
                "prop_michael_door",
                "prop_micro_cs_01_door",
                "prop_mine_doorng_l",
                "prop_mine_doorng_r",
                "prop_mineshaft_door",
                "prop_motel_door_09",
                "prop_out_door_speaker",
                "prop_outdoor_fan_01",
                "prop_paynspray_door_l",
                "prop_paynspray_door_r",
                "prop_police_door_l",
                "prop_police_door_l_dam",
                "prop_police_door_r",
                "prop_police_door_r_dam",
                "prop_police_door_surround",
                "prop_pris_door_01_l",
                "prop_pris_door_01_r",
                "prop_pris_door_02",
                "prop_pris_door_03",
                "prop_ql_revolving_door",
                "prop_ret_door",
                "prop_ret_door_02",
                "prop_ret_door_03",
                "prop_ret_door_04",
                "prop_ron_door_01",
                "prop_rub_busdoor_01",
                "prop_rub_busdoor_02",
                "prop_sc1_12_door",
                "prop_sc1_21_g_door_01",
                "prop_secdoor_01",
                "prop_sh_tt_fridgedoor",
                "prop_shop_front_door_l",
                "prop_shop_front_door_r",
                "prop_showroom_door_l",
                "prop_showroom_door_r",
                "prop_sm_10_mp_door",
                "prop_sm_27_door",
                "prop_sm_locker_door",
                "prop_sm1_11_doorl",
                "prop_sm1_11_doorr",
                "prop_ss1_05_mp_door",
                "prop_ss1_08_mp_door_l",
                "prop_ss1_08_mp_door_r",
                "prop_ss1_10_door_l",
                "prop_ss1_10_door_r",
                "prop_ss1_14_garage_door",
                "prop_ss1_mpint_door_l",
                "prop_ss1_mpint_door_r",
                "prop_strip_door_01",
                "prop_trailer_door_closed",
                "prop_trailer_door_open",
                "prop_v_door_44",
                "prop_vault_door_scene",
                "prop_wardrobe_door_01",
                "sm_hanger_smugdlc_doors",
                "sm_prop_inttruck_door_static2",
                "sm_prop_inttruck_doorblock2",
                "sm_prop_smug_hgrdoors_01",
                "sm_prop_smug_hgrdoors_02",
                "sm_prop_smug_hgrdoors_03",
                "sm_prop_smug_hgrdoors_light_a",
                "sm_prop_smug_hgrdoors_light_b",
                "sm_prop_smug_hgrdoors_light_c",
                "v_ilev_247door",
                "v_ilev_247door_r",
                "v_ilev_abbmaindoor",
                "v_ilev_abbmaindoor2",
                "v_ilev_arm_secdoor",
                "v_ilev_bank4door01",
                "v_ilev_bank4door02",
                "v_ilev_bank4doorcls01",
                "v_ilev_bank4doorcls02",
                "v_ilev_bk_door",
                "v_ilev_bk_door2",
                "v_ilev_bk_vaultdoor",
                "v_ilev_bl_door_l",
                "v_ilev_bl_door_r",
                "v_ilev_bl_doorel_l",
                "v_ilev_bl_doorel_r",
                "v_ilev_bl_doorpool",
                "v_ilev_bl_doorsl_l",
                "v_ilev_bl_doorsl_r",
                "v_ilev_bs_door",
                "v_ilev_carmod3door",
                "v_ilev_cbankcountdoor01",
                "v_ilev_cbankvauldoor01",
                "v_ilev_cd_door",
                "v_ilev_cd_door2",
                "v_ilev_cd_door3",
                "v_ilev_cd_entrydoor",
                "v_ilev_cd_secdoor",
                "v_ilev_cd_secdoor2",
                "v_ilev_cf_officedoor",
                "v_ilev_ch_glassdoor",
                "v_ilev_clothmiddoor",
                "v_ilev_cm_door1",
                "v_ilev_cor_darkdoor",
                "v_ilev_cor_doorglassa",
                "v_ilev_cor_doorglassb",
                "v_ilev_cor_doorlift01",
                "v_ilev_cor_doorlift02",
                "v_ilev_cor_firedoor",
                "v_ilev_cor_firedoorwide",
                "v_ilev_cor_offdoora",
                "v_ilev_cs_door",
                "v_ilev_cs_door01",
                "v_ilev_cs_door01_r",
                "v_ilev_csr_door_l",
                "v_ilev_csr_door_r",
                "v_ilev_csr_garagedoor",
                "v_ilev_ct_door01",
                "v_ilev_ct_door02",
                "v_ilev_ct_door03",
                "v_ilev_ct_doorl",
                "v_ilev_ct_doorr",
                "v_ilev_depboxdoor01",
                "v_ilev_dev_door",
                "v_ilev_dev_windowdoor",
                "v_ilev_deviantfrontdoor",
                "v_ilev_door_orange",
                "v_ilev_door_orangesolid",
                "v_ilev_epsstoredoor",
                "v_ilev_fa_backdoor",
                "v_ilev_fa_dinedoor",
                "v_ilev_fa_frontdoor",
                "v_ilev_fa_roomdoor",
                "v_ilev_fa_slidedoor",
                "v_ilev_fa_warddoorl",
                "v_ilev_fa_warddoorr",
                "v_ilev_fb_door01",
                "v_ilev_fb_door02",
                "v_ilev_fb_doorshortl",
                "v_ilev_fb_doorshortr",
                "v_ilev_fb_sl_door01",
                "v_ilev_fh_bedrmdoor",
                "v_ilev_fh_door01",
                "v_ilev_fh_door02",
                "v_ilev_fh_door03",
                "v_ilev_fh_door4",
                "v_ilev_fh_door5",
                "v_ilev_fh_frntdoor",
                "v_ilev_fh_frontdoor",
                "v_ilev_fh_slidingdoor",
                "v_ilev_fib_door_ld",
                "v_ilev_fib_door_maint",
                "v_ilev_fib_door1",
                "v_ilev_fib_door1_s",
                "v_ilev_fib_door2",
                "v_ilev_fib_door3",
                "v_ilev_fib_doorbrn",
                "v_ilev_fib_doore_l",
                "v_ilev_fib_doore_r",
                "v_ilev_fib_postbox_door",
                "v_ilev_fibl_door01",
                "v_ilev_fibl_door02",
                "v_ilev_fin_vaultdoor",
                "v_ilev_finelevdoor01",
                "v_ilev_gangsafedoor",
                "v_ilev_garageliftdoor",
                "v_ilev_gasdoor",
                "v_ilev_gasdoor_r",
                "v_ilev_gc_door01",
                "v_ilev_gc_door02",
                "v_ilev_gc_door03",
                "v_ilev_gc_door04",
                "v_ilev_genbankdoor1",
                "v_ilev_genbankdoor2",
                "v_ilev_gendoor01",
                "v_ilev_gendoor02",
                "v_ilev_gtdoor",
                "v_ilev_gtdoor02",
                "v_ilev_hd_door_l",
                "v_ilev_hd_door_r",
                "v_ilev_housedoor1",
                "v_ilev_j2_door",
                "v_ilev_janitor_frontdoor",
                "v_ilev_lester_doorfront",
                "v_ilev_lester_doorveranda",
                "v_ilev_lostdoor",
                "v_ilev_losttoiletdoor",
                "v_ilev_methdoorbust",
                "v_ilev_methdoorscuff",
                "v_ilev_methtraildoor",
                "v_ilev_ml_door1",
                "v_ilev_mldoor02",
                "v_ilev_mm_door",
                "v_ilev_mm_doordaughter",
                "v_ilev_mm_doorm_l",
                "v_ilev_mm_doorm_r",
                "v_ilev_mm_doorson",
                "v_ilev_mm_doorw",
                "v_ilev_moteldoorcso",
                "v_ilev_mp_high_frontdoor",
                "v_ilev_mp_low_frontdoor",
                "v_ilev_mp_mid_frontdoor",
                "v_ilev_ph_door002",
                "v_ilev_ph_door01",
                "v_ilev_ph_doorframe",
                "v_ilev_ph_gendoor",
                "v_ilev_ph_gendoor002",
                "v_ilev_ph_gendoor003",
                "v_ilev_ph_gendoor004",
                "v_ilev_ph_gendoor005",
                "v_ilev_ph_gendoor006",
                "v_ilev_phroofdoor",
                "v_ilev_po_door",
                "v_ilev_ra_door1_l",
                "v_ilev_ra_door1_r",
                "v_ilev_ra_door2",
                "v_ilev_ra_door3",
                "v_ilev_ra_door4l",
                "v_ilev_ra_door4r",
                "v_ilev_ra_doorsafe",
                "v_ilev_rc_door1",
                "v_ilev_rc_door1_st",
                "v_ilev_rc_door2",
                "v_ilev_rc_door3_l",
                "v_ilev_rc_door3_r",
                "v_ilev_rc_doorel_l",
                "v_ilev_rc_doorel_r",
                "v_ilev_roc_door1_l",
                "v_ilev_roc_door1_r",
                "v_ilev_roc_door2",
                "v_ilev_roc_door3",
                "v_ilev_roc_door4",
                "v_ilev_roc_door5",
                "v_ilev_serv_door01",
                "v_ilev_shrf2door",
                "v_ilev_shrfdoor",
                "v_ilev_sol_off_door01",
                "v_ilev_spraydoor",
                "v_ilev_ss_door01",
                "v_ilev_ss_door02",
                "v_ilev_ss_door03",
                "v_ilev_ss_door04",
                "v_ilev_ss_door5_l",
                "v_ilev_ss_door5_r",
                "v_ilev_ss_door7",
                "v_ilev_ss_door8",
                "v_ilev_ss_doorext",
                "v_ilev_stad_fdoor",
                "v_ilev_staffdoor",
                "v_ilev_store_door",
                "v_ilev_ta_door",
                "v_ilev_ta_door2",
                "v_ilev_tort_door",
                "v_ilev_tow_doorlifta",
                "v_ilev_tow_doorliftb",
                "v_ilev_trev_door",
                "v_ilev_trev_doorbath",
                "v_ilev_trev_doorfront",
                "v_ilev_trev_patiodoor",
                "v_ilev_vag_door",
                "v_ilev_vagostoiletdoor",
                "v_res_d_closetdoorl",
                "v_res_d_closetdoorr",
                "v_res_tt_fridgedoor",
                "v_ret_fh_doorframe",
                "v_ret_fh_doorfrmwide",
                "xm_int_lev_silo_doorlight_01",
                "xm_int_lev_sub_doorl",
                "xm_int_lev_sub_doorr",
                "xm_int_lev_xm17_base_door",
                "xm_int_lev_xm17_base_door_02",
                "xm_int_lev_xm17_base_doorframe",
                "xm_int_lev_xm17_base_doorframe_02",
                "xm_prop_agt_cia_door_el_02_l",
                "xm_prop_agt_cia_door_el_02_r",
                "xm_prop_agt_cia_door_el_l",
                "xm_prop_agt_cia_door_el_r",
                "xm_prop_agt_door_01",
                "xm_prop_base_blast_door_01",
                "xm_prop_base_blast_door_01a",
                "xm_prop_base_blast_door_02_l",
                "xm_prop_base_blast_door_02_r",
                "xm_prop_base_blast_door_02a",
                "xm_prop_base_cabinet_door_01",
                "xm_prop_base_door_02",
                "xm_prop_base_door_04",
                "xm_prop_base_doorlamp_lock",
                "xm_prop_base_doorlamp_unlock",
                "xm_prop_base_heavy_door_01",
                "xm_prop_base_slide_door",
                "xm_prop_cannon_room_door",
                "xm_prop_cannon_room_door_02",
                "xm_prop_facility_door_01",
                "xm_prop_facility_door_02",
                "xm_prop_iaa_base_door_01",
                "xm_prop_iaa_base_door_02",
                "xm_prop_int_avenger_door_01a",
                "xm_prop_lab_door01_dna_l",
                "xm_prop_lab_door01_dna_r",
                "xm_prop_lab_door01_l",
                "xm_prop_lab_door01_lbth_l",
                "xm_prop_lab_door01_lbth_r",
                "xm_prop_lab_door01_r",
                "xm_prop_lab_door01_stack_l",
                "xm_prop_lab_door01_stack_r",
                "xm_prop_lab_door01_star_l",
                "xm_prop_lab_door01_star_r",
                "xm_prop_lab_door02_r",
                "xm_prop_lab_doorframe01",
                "xm_prop_lab_doorframe02",
                "xm_prop_silo_elev_door01_l",
                "xm_prop_silo_elev_door01_r",
                "xm_prop_x17_add_door_01",
                "xm_prop_x17_bunker_door",
                "xm_prop_x17_l_door_frame_01",
                "xm_prop_x17_l_door_glass_01",
                "xm_prop_x17_l_door_glass_op_01",
                "xm_prop_x17_silo_door_l_01a",
                "xm_prop_x17_silo_door_r_01a",

        };

        public static List<string> PedBone = new List<string>()
        {
            "SKEL_ROOT",
            "FB_R_Brow_Out_000",
            "SKEL_L_Toe0",
            "SKEL_L_Finger01",
            "MH_R_Elbow",
            "SKEL_L_Finger02",
            "SKEL_L_Finger31",
            "SKEL_L_Finger32",
            "SKEL_L_Finger41",
            "SKEL_L_Finger42",
            "SKEL_L_Finger11",
            "SKEL_L_Finger12",
            "SKEL_L_Finger21",
            "SKEL_L_Finger22",
            "RB_L_ArmRoll",
            "IK_R_Hand",
            "RB_R_ThighRoll",
            "SKEL_R_Clavicle",
            "FB_R_Lip_Corner_000",
            "SKEL_Pelvis",
            "IK_Head",
            "SKEL_L_Foot",
            "MH_R_Knee",
            "FB_LowerLipRoot_000",
            "FB_R_Lip_Top_000",
            "SKEL_L_Hand",
            "FB_R_CheekBone_000",
            "FB_UpperLipRoot_000",
            "FB_L_Lip_Top_000",
            "FB_LowerLip_000",
            "SKEL_R_Toe0",
            "FB_L_CheekBone_000",
            "MH_L_Elbow",
            "SKEL_Spine0",
            "RB_L_ThighRoll",
            "PH_R_Foot",
            "SKEL_Spine1",
            "SKEL_Spine2",
            "SKEL_Spine3",
            "FB_L_Eye_000",
            "SKEL_L_Finger00",
            "SKEL_L_Finger10",
            "SKEL_L_Finger20",
            "SKEL_L_Finger30",
            "SKEL_L_Finger40",
            "FB_R_Eye_000",
            "SKEL_R_Forearm",
            "PH_R_Hand",
            "FB_L_Lip_Corner_000",
            "SKEL_Head",
            "IK_R_Foot",
            "RB_Neck_1",
            "IK_L_Hand",
            "SKEL_R_Calf",
            "RB_R_ArmRoll",
            "FB_Brow_Centre_000",
            "SKEL_Neck_1",
            "SKEL_R_UpperArm",
            "FB_R_Lid_Upper_000",
            "RB_R_ForeArmRoll",
            "SKEL_L_UpperArm",
            "FB_L_Lid_Upper_000",
            "MH_L_Knee",
            "FB_Jaw_000",
            "FB_L_Lip_Bot_000",
            "FB_Tongue_000",
            "FB_R_Lip_Bot_000",
            "SKEL_R_Thigh",
            "SKEL_R_Foot",
            "IK_Root",
            "SKEL_R_Hand",
            "SKEL_Spine_Root",
            "PH_L_Foot",
            "SKEL_L_Thigh",
            "FB_L_Brow_Out_000",
            "SKEL_R_Finger00",
            "SKEL_R_Finger10",
            "SKEL_R_Finger20",
            "SKEL_R_Finger30",
            "SKEL_R_Finger40",
            "PH_L_Hand",
            "RB_L_ForeArmRoll",
            "SKEL_L_Forearm",
            "FB_UpperLip_000",
            "SKEL_L_Calf",
            "SKEL_R_Finger01",
            "SKEL_R_Finger02",
            "SKEL_R_Finger31",
            "SKEL_R_Finger32",
            "SKEL_R_Finger41",
            "SKEL_R_Finger42",
            "SKEL_R_Finger11",
            "SKEL_R_Finger12",
            "SKEL_R_Finger21",
            "SKEL_R_Finger22",
            "SKEL_L_Clavicle",
            "FACIAL_facialRoot",
        };


        /*0 = Front Left Door  
        1 = Front Right Door  
        2 = Back Left Door  
        3 = Back Right Door  
        4 = Hood  
        5 = Trunk  
        6 = Back  
        7 = Back2*/

        public static List<string> VehicleDoorBone = new List<string>()
        {
                "handle_dside_f",
                "handle_pside_f",
                "handle_dside_r",
                "handle_pside_r",
                "engine",
                "platelight",
                "chassis_dummy",
                "boot",
        };

        public static List<string> VehicleBone = new List<string>() {
               "bonnet",
                "bumper_f",
                "bumper_r",
                "door_dside_f",
                "window_lf",
                "handle_dside_f",
                "door_dside_r",
                "window_lr",
                "handle_dside_r",
                "window_rr",
                "handle_pside_r",
                "window_rf",
                "handle_pside_f",
                "windscreen_r",
                "windscreen",
                "suspension_lr",
                "suspension_lf",
                "suspension_rf",
                "suspension_rr",
                "wing_lf",
                "wing_lf",
                "boot",
                "reversinglight_r",
                "reversinglight_l",
                "platelight",
                "indicator_rr",
                "indicator_lr",
                "indicator_lf",
                "indicator_rf",
                "headlight_r",
                "headlight_l",
                "taillight_l",
                "taillight_r",
                "engine",
                "exhaust",
                "exhaust_2",
                "seat_dside_f",
                "seat_dside_f",
                "seat_pside_r",
                "seat_pside_r",
                "overheat_2",
                "overheat",
                "interiorlight",
                "hub_lf",
                "hub_rf",
                "hub_lr",
                "hub_rr",
                "wheel_lf",
                "wheelmesh_lf",
                "wheelmesh_lf_l1",
                "wheelmesh_lf_l2",
                "wheelmesh_lf_ng",
                "wheel_lr",
                "wheel_rr",
                "wheel_rf",
                "bodyshell",
                "misc_a",
                "misc_b",
                "slipstream_l",
                "slipstream_r",
                "neon_l",
                "neon_r",
                "neon_f",
                "neon_b",
                "dashglow",
                "steeringwheel",
                "dials",
                "chassis_dummy",

            };

    }
}
